taco:
  orders:
    pageSize: 10
logging:
  level:
    tacos: debug
spring:
  data:
    rest:
      base-path: /api
#---
#spring:
#  profiles: prod
#  datasource:
#    url: jdbc:mysql://localhost/tacocloud
#    username: tacouser
#    password: tacopassword
#logging:
#  level:
#    tacos: warn