taco:
  orders:
    pageSize: 10
logging:
  level:
    tacos: debug
spring:
  data:
    rest:
      base-path: /api
  jms:
    template:
      default-destination: tacocloud.order.qeue
  artemis:
    password: 1234
    user: tacoweb
#---
#spring:
#  profiles: prod
#  datasource:
#    url: jdbc:mysql://localhost/tacocloud
#    username: tacouser
#    password: tacopassword
#logging:
#  level:
#    tacos: warn